### ISSUE TITLE
[Docs] Import.js: Where does it go?

### ISSUE THREAD

**Issue by badvision** [adobe/helix-importer-ui#187]
### Expected Behaviour
Documentation should be clear

### Actual Behaviour
Documentation literally tells you everything about the import.js file you need to write except where to actually put it so it is usable.

### Reproduce Scenario (including but not limited to)
N/A (documentation issue)

#### Steps to Reproduce
Scan the documentation looking for references to folders and directories -- none are mentioned with regard to where import.js needs to reside.

**Comment by catalan-adobe** [comment]
Good catch @badvision! PR #192 is a proposal to get this point clarified.
