### ISSUE TITLE
[Import] Some <u> tags dissapear from the final word doc in spite of appearing in the preview

### ISSUE THREAD

**Issue by sharmrj** [adobe/helix-importer-ui#198]
### Expected Behaviour
Upon importing this page: https://helpx-internal.corp.adobe.com/content/help/en/internal/individual/policy-process/workaround-for-mfa--multi-factor-authentication--issue.html
The following preview is shown (only the relevant part for brevity's sake-- Notice the line `<u>SME process with IMS Team (new)</u>`):
 ![](https://files.slack.com/files-pri/T23RE8G4F-F05ALF899T7/screenshot_2023-06-02_at_3.42.00_pm.png)

It is expected that the saved word document will also contain the line `<u>SME process with IMS Team (new)</u>`

### Actual Behaviour

The line in question disappears from the saved word document:
![](https://files.slack.com/files-pri/T23RE8G4F-F05A8TP62A3/screenshot_2023-06-02_at_3.45.46_pm.png)

It should be noted that not all <u> tags dissappear, only one (that I've noticed)

#### Steps to Reproduce

1. Run the helix importer
2. Import https://helpx-internal.corp.adobe.com/content/help/en/internal/individual/policy-process/workaround-for-mfa--multi-factor-authentication--issue.html
3. See if the line is missing from the word document.

#### Platform and Version
`helix-import-ui@1.41.0`

**Comment by kptdobe** [comment]
This was fixed by https://github.com/adobe/helix-md2docx/issues/270
