### ISSUE TITLE
Distinguish between redirects to a different domain and errors

### ISSUE THREAD

**Issue by shsteimer** [adobe/helix-importer-ui#233]
### Expected Behaviour

When importing, if a page issues a redirect to a different domain, it is reported as an unknown status code error.

### Actual Behaviour

These should be reported as redirects.

### Reproduce Scenario (including but not limited to)

Compare import of these 2 pages:
- https://www.stewart.com/en/stewart-uk/home.html (returns 301 to https://www.stewarttitle.co.uk/en/stewart-uk/home.html but reported as an error)
- https://www.stewart.com/en/underwriting.html (returned 301 to https://www.stewart.com/en/legal-contacts/underwriting-counsel.html reported as redirect)

**Comment by shsteimer** [comment]
further investigation reveals that this is actually related to CORS, occurs here https://github.com/adobe/helix-importer-ui/blob/main/js/import/import.ui.js#L450

```
Access to fetch at 'https://investors.stewart.com/governance/board-of-directors/default.aspx' (redirected from 'http://localhost:3001/en/about-stewart/corporate-leadership/board-of-directors.html?host=https%3A%2F%2Fwww.stewart.com') from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Wonder if it's possible/would make sense to rather than having fetch follow the redirects, so send that request with `redirect: 'manual'`, and then check the response code/location header for dealing with redirects?

**Comment by kptdobe** [comment]
Closing for now. 
I think the redirect to another host would be complicated to handle: the proxy should detect this case and also proxy the new host. 
Workaround: provide the final url in the importer ui and not the one which will redirect...
@shsteimer Feel free to reopen if you think this is really something to be addressed.
