### ISSUE TITLE
Preserve Import Report in Local storage

### ISSUE THREAD

**Issue by synox** [adobe/helix-importer-ui#257]
When I import 1000+ pages, the tab eventually crashes. After the crash, I can not access the import report. But without the import report I can not use the import, because I need the logged parameters. 

### Expected Behaviour
The import report should survive a crash. e.g. by using local storage. 

### Actual Behaviour
After a crash, all the progress is lost. 

### Workaround
Right now I download the excel file every few minutes, so I have a recent snapshot to work with. 
But this is also difficult because the green Toast message covers the button, so I can't even press it.

**Comment by kptdobe** [comment]
Humm... in bulk mode, the import report should be automatically downloaded in the target folder. See https://github.com/adobe/helix-importer-ui/pull/104
Tell me if this is not the case.

**Comment by synox** [comment]
oh, I was not aware. Thanks!
