### ISSUE TITLE
invalid "Transformation file URL" should throw an error

### ISSUE THREAD

**Issue by synox** [adobe/helix-importer-ui#258]
I don't like the behavior when having a typo in the url. 

### Expected Behaviour
It should show an error: "Tranformation file not found"

### Actual Behaviour
An import it run with the default config, and overrides any existing word documents.

**Comment by kptdobe** [comment]
No import file is a valid use case ("default import") and you can easily see in the console log that the file cannot be found (red 404 error). 
Maybe simply showing a message like "No transformation file found, using the default one" to inform the user could be a good compromise.
