### ISSUE TITLE
[import] Hot reload imported files

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-importer-ui#267]
If your import.js script has local imports, they are not hot reloaded when changed. A full page reload is required. 
The workaround to speed up development is to put everything in one script.
Another workaround could be to have a rollup or webpack script to bundle the import.js and its dependencies in on single file and run a watcher that will reconstruct the file on change. This requires some bundling knowledge.

Ideally, this would be managed automatically by the importer.

**Comment by atopper** [comment]
A non-code solution could be done as follows by the person importing:
- ensure `esbuild` is install and accessible
- on a command line, start `esbuild` as follows (varying paths and/or parameters as required):
  - `node_modules\.bin\esbuild import.js --bundle --outdir=importjs --watch`
  - that will watch for changes on `import.js` and all its imports, bundling them in the outdir
- in the UI, change the `import.js` indicated to the one that is built in the output dir `importjs` folder

This will catch changes in all the files in the `pollimport.js` file.

@kptdobe - should I write up this idea in README.md?  Somewhere else more appropriate?

**Comment by kptdobe** [comment]
Nice... writing the instructions somewhere in the doc (https://github.com/adobe/helix-importer-ui/blob/main/importer-guidelines.md#advanced section ?) would be a good intermediate step! Thanks @atopper.

**Comment by atopper** [comment]
A section was added to [importer-guidelines.md](https://github.com/adobe/helix-importer-ui/blob/main/importer-guidelines.md) in 'Advanced'.  I'll leave this issue open though, in case someone is able to do a solution in code.

**Comment by kptdobe** [comment]
We can close the issue. If someone is not happy with the workaround and wants to provide a PR, feel free to reopen the issue.
