### ISSUE TITLE
fix: Potential Cross‐Site Scripting in Helix Importer UI [AEM-06]

### ISSUE THREAD

**Issue by rofe** [adobe/helix-importer-ui#279]
Follow up to #128 from remediation:

We noted that there was at least one instance that was vulnerable to XSS. In the Eyedropper, it is possible for a user to select a logo to copy and download. The logo selection relies on `innerHtml` if the element starts with `<svg`.

Therefore, using the Eyedropper to load the following page:
```xml
<svg id=x onfocus=alert(1)><rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" /></svg>
```

Then using the logo selection tool to select the blue rectangle and click on the new blue rectangle triggers the XSS (despite the Enable JavaScript option disabled):
<img width="973" alt="image" src="https://github.com/adobe/helix-importer-ui/assets/1609742/1e9fece7-6ba2-4cde-9cd1-429eed397f84">

**Comment by kptdobe** [comment]
Was fixed by https://github.com/adobe/helix-importer-ui/pull/280
