### ISSUE TITLE
[Import Service] Initiate a bulk import using Spacecat service

### ISSUE THREAD

**Issue by arumsey** [adobe/helix-importer-ui#398]
Use the Spacecat [import](https://opensource.adobe.com/spacecat-api-service/#tag/import) endpoint to initiate a bulk import operation.

- add an option within **Import- Bulk** to use service
- include api key as additional input
- include status (status, url count, success count, failed count)
- include a button to download ZIP file

**Comment by blefebvre** [comment]
Should there be a button to check / refresh the status? Or will the importer UI poll the service?

**Comment by arumsey** [comment]
> Should there be a button to check / refresh the status? Or will the importer UI poll the service?

I think there should be a button to refresh the status. Polling could be explored as well.

Also, we should consider managing multiple import jobs and how each job can be tracked separately.

**Comment by blefebvre** [comment]
One import job per API key is a restriction we have in place currently to prevent abuse of the service.

**Comment by atopper** [comment]
I'd suggest a slow status poll (every 5 minutes?) with a refresh button.  If it takes hours, we don't need constant updates.

**Comment by arumsey** [comment]
Closing since https://labs.aem.live/import is now available.
